### ISSUE TITLE
Forked tests cause NPE

### ISSUE THREAD

**Issue by ewiner** [guardian/sbt-teamcity-test-reporting-plugin#1]
When you specify fork := true in your build, the TestEvent.error() value always returns null.  This causes a NullPointerException inside nicelyFormatException().

**Comment by philwills** [comment]
Hi, with the upgrade to work with 0.13, we're now given an OptionalThrowable, which we do a definedness check against https://github.com/guardian/sbt-teamcity-test-reporting-plugin/blob/master/src/main/scala/com/gu/TeamCityTestReporting.scala#L25, so I believe this should be fixed.
